<a href="https://colab.research.google.com/github/ArpulaAnjali/AIML/blob/main/Lab%201" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
names=['palomi','ashu','deepa','anjali']
print(names)
print(type(names))
print(len(names))

['palomi', 'ashu', 'deepa', 'anjali']
<class 'list'>
4


In [2]:
import numpy as np
num_array=np.array([1,2,3,4])
print(num_array)
print(type(num_array))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
num=np.array([1,2,3,4])
print(type(num))

<class 'numpy.ndarray'>


In [4]:
import numpy as np
array1=np.array([3,4,5,6])
array2=np.array([2,5,6,7])
print(array1*array2)
print(array1/array2)
print(np.power(array1,2))

[ 6 20 30 42]
[1.5        0.8        0.83333333 0.85714286]
[ 9 16 25 36]


In [5]:
import numpy as np
array1=np.array([3,4,5,6])
array2=np.array([2,5,6,7])
print("addition of two:",array1+array2)

addition of two: [ 5  9 11 13]


In [6]:
import numpy as np
my_array=np.array([1,2,3,4,5])
sin=np.sin(my_array)
print(sin)
log=np.log(my_array)
print(log)
log2=np.log2(my_array)
print(log2)
exp=np.exp(my_array)
print(exp)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
